/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	bucket_v1 "github.com/yuankunzhang/devops-challenge/kube-bucket/pkg/apis/bucket/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBuckets implements BucketInterface
type FakeBuckets struct {
	Fake *FakeStoragek8sV1
	ns   string
}

var bucketsResource = schema.GroupVersionResource{Group: "storagek8s.honestbee.io", Version: "v1", Resource: "buckets"}

var bucketsKind = schema.GroupVersionKind{Group: "storagek8s.honestbee.io", Version: "v1", Kind: "Bucket"}

// Get takes name of the bucket, and returns the corresponding bucket object, and an error if there is any.
func (c *FakeBuckets) Get(name string, options v1.GetOptions) (result *bucket_v1.Bucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bucketsResource, c.ns, name), &bucket_v1.Bucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bucket_v1.Bucket), err
}

// List takes label and field selectors, and returns the list of Buckets that match those selectors.
func (c *FakeBuckets) List(opts v1.ListOptions) (result *bucket_v1.BucketList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bucketsResource, bucketsKind, c.ns, opts), &bucket_v1.BucketList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &bucket_v1.BucketList{ListMeta: obj.(*bucket_v1.BucketList).ListMeta}
	for _, item := range obj.(*bucket_v1.BucketList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested buckets.
func (c *FakeBuckets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bucketsResource, c.ns, opts))

}

// Create takes the representation of a bucket and creates it.  Returns the server's representation of the bucket, and an error, if there is any.
func (c *FakeBuckets) Create(bucket *bucket_v1.Bucket) (result *bucket_v1.Bucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bucketsResource, c.ns, bucket), &bucket_v1.Bucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bucket_v1.Bucket), err
}

// Update takes the representation of a bucket and updates it. Returns the server's representation of the bucket, and an error, if there is any.
func (c *FakeBuckets) Update(bucket *bucket_v1.Bucket) (result *bucket_v1.Bucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bucketsResource, c.ns, bucket), &bucket_v1.Bucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bucket_v1.Bucket), err
}

// Delete takes name of the bucket and deletes it. Returns an error if one occurs.
func (c *FakeBuckets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bucketsResource, c.ns, name), &bucket_v1.Bucket{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBuckets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bucketsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &bucket_v1.BucketList{})
	return err
}

// Patch applies the patch and returns the patched bucket.
func (c *FakeBuckets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *bucket_v1.Bucket, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bucketsResource, c.ns, name, data, subresources...), &bucket_v1.Bucket{})

	if obj == nil {
		return nil, err
	}
	return obj.(*bucket_v1.Bucket), err
}
